### ISSUE TITLE
How to run your code

### ISSUE THREAD

**Issue by RiccoSuave** [addaleax/munkres-js#6]
Hi
I have cloned your code and am trying to run it. Would you outline the steps please? 
sansari@karbela:~/munkres$ tree 
.
└── munkres-js
    ├── bower.json
    ├── CHANGELOG
    ├── example.html
    ├── LICENSE
    ├── munkres.js
    ├── package.json
    ├── README.md
    └── test
        └── test.js

2 directories, 8 files

**Comment by addaleax** [comment]
Hi @RiccoSuave ! There’s an [example script](https://github.com/addaleax/munkres-js#usage) in the readme file, you should be able to run that by putting it in a `.js` file, installing this module as `npm install munkres-js` and then running your script via `node <filename>`… does that work for you?

**Comment by RiccoSuave** [comment]
yes:-) Thanks.

**Comment by addaleax** [comment]
Ok, great! Let me know if you have any other questions.
